Controllers/ImplementController.cs
using Microsoft.AspNetCore.Mvc;
using PCNW.Data.Repository;
using PCNW.Helpers;
using PCNW.Models;
using PCNW.Models.ContractModels;
using PCNW.ViewModel;

namespace PCNW.Controllers
{
    public class ImplementController : BaseController
    {
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly IImplementRepository _implementRepository;
        private readonly ICommonRepository _commonRepository;
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _environment;
        private readonly ILogger<ImplementController> _logger;
        private readonly IEntityRepository _entityRepository;

        public ImplementController(ApplicationDbContext applicationDbContext, ICommonRepository commonRepository, IImplementRepository implementRepository, Microsoft.AspNetCore.Hosting.IHostingEnvironment environment, ILogger<ImplementController> logger, IEntityRepository entityRepository)
        {
            _applicationDbContext = applicationDbContext;
            _implementRepository = implementRepository;
            _environment = environment;
            _commonRepository = commonRepository;
            _logger = logger;
            _entityRepository = entityRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult AutoComplete(string prefix)
        {
            HttpResponseDetail<dynamic> response = new();
            var result = _implementRepository.AutoCompleteAsync(prefix);
            response.data = result;
            return Json(response);
        }
        [HttpPost]
        public JsonResult GetProjectCode()
        {
            HttpResponseDetail<dynamic> response = new();
            var result = _implementRepository.GetProjectCodeAsync();
            response.data = result;
            return Json(response);
        }
        /// <summary>
        /// No use just testing purpose
        /// </summary>
        /// <returns></returns>
        public IActionResult UploadPdf()
        {
            return View();
        }
        /// <summary>
        /// Get company name suggestion on print order form of staff copy center and staff preview page
        /// </summary>
        /// <param name="prefix"></param>
        /// <returns></returns>
        public JsonResult GetCompanyName(string prefix)
        {
            dynamic result = null;
            if (!string.IsNullOrEmpty(prefix))
            {
                result = (from member in _entityRepository.GetEntities()
                          where member.Company.StartsWith(prefix)
                          select new
                          {
                              label = member.Company,
                              val = member.Id
                          }).ToList();
            }
            else
            {
                result = (from member in _entityRepository.GetEntities()
                          select new
                          {
                              label = member.Company,
                              val = member.Id
                          }).ToList();
            }
            return Json(result);
        }
        /// <summary>
        /// Get company address on preview(staffaccount page) print order form, staff copy center
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public JsonResult GetCompanyAddress(int Id)
        {
            HttpResponseDetail<dynamic> response = new();
            var result = _implementRepository.GetCompanyAddress(Id);
            response.data = result;
            return Json(response);
        }
        /// <summary>
        /// No use
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> GetStateList()
        {
            HttpResponseDetail<dynamic> response = new();
            var result = await _implementRepository.GetStates();
            response.data = result;
            return Json(response);
        }
        /// <summary>
        /// No use
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public JsonResult GetContactName(int Id)
        {
            var response = _implementRepository.GetCompanyAddress(Id);
            List<SelectedInfo> result = new();
            if (Id != 0)
            {
                try
                {
                    result = response.ContactList.Select(x => new SelectedInfo
                    {
                        label = x.Contact,
                        val = x.UID
                    }).ToList();
                }
                catch (Exception ex)
                {
                    _logger.LogInformation(ex.Message);
                }
            }
            else
            {
                result.Add(new SelectedInfo { label = "", val = "0" });
            }
            return Json(result);
        }
        /// <summary>
        /// Get the list of state which is present in active project list on find project here state list and also in geographical search
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> GetDistinctState()
        {
            HttpResponseDetail<dynamic> response = new();
            var result = await _implementRepository.GetDistinctState();
            response.data = result;
            return Json(response);
        }
        public async Task<JsonResult> GetDistinctStateOfTab(int SelectedTab)
        {
            DisplayLoginInfo info = _commonRepository.GetUserInfo(User.Identity.Name);
            HttpResponseDetail<dynamic> response = new();
            var result = await _implementRepository.GetDistinctStateOfTab(Convert.ToInt32(SelectedTab), info);
            response.data = result;
            return Json(response);
        }
    }
}

Views/Implement/Index.cshtml
@{
    ViewData["Title"] = "Demo Page";
    Layout = "~/Views/Shared/_Layout-admin.cshtml";

}
@section CustomCSS{
    <style>
        fieldset#autocomplete {
            border: solid 1px #E6E6E6;
            padding: 0 20px;
        }

            fieldset#autocomplete legend {
                width: 37%;
            }
    </style>
}

    @section Scripts{
    <script type="text/javascript">
        var jq = jQuery.noConflict();
        jq(function () {
            jq("#txtCustomer").autocomplete({
                source: function (request, response) {
                    jq.ajax({
                        url: '/Implement/AutoComplete/',
                        data: { "prefix": request.term },
                        type: "POST",
                        async: false,
                        success: function (response) {
                            response(jq.map(response.data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            console.log(response.responseText);
                        },
                        failure: function (response) {
                            console.log(response.responseText);
                        }
                    });
                },
                select: function (e, i) {
                    jq("#hfCustomer").val(i.item.val);
                },
                minLength: 0
            }).focus(function () {
                jq(this).autocomplete("search");
            });
        });
    </script>
    <script>
        function GetProjCode() {
            jq.ajax({
                url: '/Implement/GetProjectCode/',
                data: {},
                type: "POST",
                success: function (response) {
                    jq('#ProjectCode').val(response.data);
                },
                error: function (response) {
                    alert(response.statusMessage);
                },
                failure: function (response) {
                    alert(response.statusMessage);
                }
            });
        }
        GetProjCode();
    </script>
    <script>
        jq(document).ready(function(){
            jq('#BtnUpload').on('click', function () {
                var input = document.getElementById("files");
                var reader = new FileReader();
                reader.readAsBinaryString(input.files[0]);
                reader.onloadend = function () {
                    var count = reader.result.match(/\/Type[\s]*\/Page[^s]/g).length;
                    console.log('Number of Pages:', count);
                }
                console.log('file uploaded');
            });
        });
    </script>
}

    <div class="top-heading" style="padding: 25px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 style="padding-top: 15px;font-size:30px;">AutoComplete Demo Page</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="mainBox">
        <div class="container">
            <div class="col-md-12">
                <div class="col-md-4">
                    <fieldset id="autocomplete">
                        <legend>AutoComplete</legend>
                        <form class="form">
                            <input type="text" id="txtCustomer" name="CustomerName" />
                            <input type="hidden" id="hfCustomer" name="CustomerId" />
                            <br />
                            <br />
                            <input type="submit" id="btnSubmit" value="Submit" />
                            <br />
                            <br />
                            @ViewBag.Message
                        </form>
                    </fieldset>
                </div>
                <div class="col-md-4">
                    <fieldset id="autocomplete">
                        <legend>Project Number</legend>
                        <form class="form">
                            <input type="text" id="ProjectCode" name="ProjectCode" />
                        </form>
                    </fieldset>
                </div>
                <div class="col-md-4">
                    <fieldset class="file-uploder-class">
                        <legend>Upload Files</legend>
                        <form class="form">
                            <input type="file" id="files" name="files" />
                            <input type="button" id="BtnUpload" name="BtnUpload" class="btn btn-primary" value="Upload Document" />
                        </form>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>

Views/Implement/UploadPdf.cshtml
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers;
@{
    ViewData["Title"] = "Upload Pdf File Information";
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>JS Bin</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.1/es6-shim.js"></script>
    <script src="https://code.jquery.com/jquery-2.1.4.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://frontenddeveloping.github.io/pdfjs-dist/build/pdf.js"></script>
    <script src="https://frontenddeveloping.github.io/pdfjs-dist/build/pdf.worker.js"></script>
    <script>
        $(document).ready(function () {
            $("#uploader").on('change', function () {
                var files = $('#uploader').prop("files");
                var url = "/Implement?handler=MyUploader";
                formData = new FormData();
                formData.append("MyUploader", files[0]);

                jQuery.ajax({
                    type: 'POST',
                    url: url,
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("XSRF-TOKEN",
                            $('input:hidden[name="__RequestVerificationToken"]').val());
                    },
                    success: function (repo) {
                        if (repo.status == "success") {
                            alert("File : " + repo.filename + " is uploaded successfully");
                        }
                    },
                    error: function () {
                        alert("Error occurs");
                    }
                });
            });

            // If you want to upload file on button click, then use below button click event
            $("#btnUpload").on('click', function () {
                // add jQuery ajax code to upload
            });
        });
    </script>
    <script type="text/javascript">
        function AjaxFormSubmit() {
            //Set the URL.
            var url = $("#myForm").attr("action");
            //Add the Field values to FormData object.
            var formData = new FormData();
            formData.append("firstName", $("#txtFirstName").val());
            formData.append("lastName", $("#txtLastName").val());
            formData.append("postedFile1", $("#fuPhoto")[0].files[0]);
            formData.append("postedFile2", $("#fuDocument")[0].files[0]);

            $.ajax({
                type: 'POST',
                url: url,
                data: formData,
                processData: false,
                contentType: false
            }).done(function (response) {
                if (response.Status === "success") {
                    $("#lblMessage").html(response.Message);
                }
            });
        }
    </script>
</head>
<body>

    <div class="container">
        <p>Select pdf file to check number of pages and links inside.</p>
        @*<form>*@
        <div class="row">
            <h2>Upload file using jQuery ajax in Asp.net Core Razor Pages</h2>

            <div class=" form-group  text-center offset-3">
                <div class="custom-file">
                    <input type="file" id="uploader" class="uploader">
                    <button id="btnUpload" class="btn btn-success">Upload</button>
                </div>
            </div>
        </div>
        @*</form>*@
    </div>
    <div class="container">
        <form id="myForm" method="post" enctype="multipart/form-data" asp-controller="Implement" asp-action="UploadPdf">
            <table>
                <tr>
                    <td>First Name: </td>
                    <td><input type="text" id="txtFirstName" /></td>
                </tr>
                <tr>
                    <td>Last Name: </td>
                    <td><input type="text" id="txtLastName" /></td>
                </tr>
                <tr>
                    <td>Photo: </td>
                    <td><input id="fuPhoto" type="file" name="postedFile1" /></td>
                </tr>
                <tr>
                    <td>Document: </td>
                    <td><input id="fuDocument" type="file" name="postedFile2" /></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="button" value="Submit" onclick="AjaxFormSubmit()" /></td>
                </tr>
            </table>
            <hr />
            <span id="lblMessage"></span>
        </form>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">PDF info</h4>
                </div>
                <div class="modal-body">
                    <p>Pages: <span class="pdf-pages">in progress</span></p>
                    <p>Links: <span class="pdf-links">in progress</span></p>
                </div>
            </div>
        </div>
    </div>

    <script id="jsbin-javascript">
        function processAnnotations(annotationsData) {
            for (var i = 0; i < annotationsData.length; i++) {
                var data = annotationsData[i];
                if (!data) {
                    continue;
                }
                if (data.subtype === 'Link') {
                    linkCounter++;
                }
            }
        }
        function readPDFFile(pdf) {
            PDFJS.getDocument({ data: pdf }).then(function (pdf) {
                $pdfPages.text(pdf.pdfInfo.numPages);
                var pagesPromisesArray = new Array(pdf.pdfInfo.numPages + 1).join('0').split('').map(function (value, index) {
                    return pdf.getPage(++index);
                });

                Promise.all(pagesPromisesArray).then(function (pages) {
                    var pagesAnnotationsPromisesArray = pages.map(function (page) {
                        return page.getAnnotations();
                    });
                    Promise.all(pagesAnnotationsPromisesArray).then(function (annotationsDataArray) {
                        annotationsDataArray.forEach(function (pageAnnotationsData) {
                            processAnnotations(pageAnnotationsData);
                        });
                        $pdfLinks.text(linkCounter);
                        $modal.modal('show')
                    });
                });
            });
        }
        var linkCounter;
        var $modal = $('.modal').modal('hide');
        var $pdfPages = $modal.find('.pdf-pages');
        var $pdfLinks = $modal.find('.pdf-links');
        window.onload = function () {
            document.getElementById('uploader').addEventListener('change', function () {
                var file = this.files[0];
                linkCounter = 0;
                if (!file) {
                    return;
                }
                var fileReader = new FileReader();
                fileReader.onload = function (e) {
                    readPDFFile(new Uint8Array(e.target.result));
                };
                fileReader.readAsArrayBuffer(file);
            });
        };
    </script>



    <script id="jsbin-source-javascript" type="text/javascript">
        function processAnnotations(annotationsData) {
            for (var i = 0; i < annotationsData.length; i++) {
                var data = annotationsData[i];
                if (!data) {
                    continue;
                }
                if (data.subtype === 'Link') {
                    linkCounter++;
                }
            }
        }
        function readPDFFile(pdf) {
            PDFJS.getDocument({ data: pdf }).then(function (pdf) {
                $pdfPages.text(pdf.pdfInfo.numPages);
                var pagesPromisesArray = new Array(pdf.pdfInfo.numPages + 1).join('0').split('').map(function (value, index) {
                    return pdf.getPage(++index);
                });

                Promise.all(pagesPromisesArray).then(function (pages) {
                    var pagesAnnotationsPromisesArray = pages.map(function (page) {
                        return page.getAnnotations();
                    });
                    Promise.all(pagesAnnotationsPromisesArray).then(function (annotationsDataArray) {
                        annotationsDataArray.forEach(function (pageAnnotationsData) {
                            processAnnotations(pageAnnotationsData);
                        });
                        $pdfLinks.text(linkCounter);
                        $modal.modal('show')
                    });
                });
            });
        }
        var linkCounter;
        var $modal = $('.modal').modal('hide');
        var $pdfPages = $modal.find('.pdf-pages');
        var $pdfLinks = $modal.find('.pdf-links');
        window.onload = function () {
            document.getElementById('uploader').addEventListener('change', function () {
                var file = this.files[0];
                linkCounter = 0;
                if (!file) {
                    return;
                }
                var fileReader = new FileReader();
                fileReader.onload = function (e) {
                    readPDFFile(new Uint8Array(e.target.result));
                };
                fileReader.readAsArrayBuffer(file);
            });
        };
    </script>
</body>
</html>